apiVersion: v1
kind: Pod
metadata:
  name: charlie-pod-conda-py
  labels:
    type: charlie
spec:
  containers:
    - name: charlie
      image: vinodh363656/python-kube-client:1.0.0
      tty: true
      resources:
        limits:
          cpu: 150m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
