apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    type: sample
spec:
  containers:
    - name: sample
      image: alpine:latest
      tty: true
      resources:
        limits:
          cpu: 150m
          memory: 200Mi
        requests:
          cpu: 100m
          memory: 100Mi
